name: Push on Release 

on:
    release:
      types: [created]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write
    deployments: write

jobs:
    prepareVersion:
        runs-on: windows-latest
        timeout-minutes: 15
        outputs:
            versionString: ${{ steps.get_version.outputs.version-without-v }}
            fullVersionString: ${{ steps.get_version.outputs.version}}
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                fetch-depth: 0 # Mandatory to use the extract version from tag action
        
            - name: Extract version from tag
              id: get_version
              env:
                VERSION: ${{ github.ref_name }}
              shell: pwsh
              run: |
                $version = $env:VERSION
                "version=$version" >> $env:GITHUB_OUTPUT
                "version-without-v=$($version -replace '^v', '')" >> $env:GITHUB_OUTPUT
                          
    call-build-workflow:
        uses: ./.github/workflows/Build.yml
        needs: prepareVersion
        with:
            version: ${{needs.prepareVersion.outputs.versionString}}
            runs-on: windows-latest
        secrets: inherit

    call-publish-workflow-version:
        needs: [prepareVersion,call-build-workflow]
        uses: ./.github/workflows/publish.yml
        with:
            nexus-path: https://lieberlieber.nexus/repository/lemontree-pipeline-tools/${{needs.prepareVersion.outputs.fullVersionString}}
        secrets: inherit

    call-publish-workflow:
      needs: [prepareVersion,call-build-workflow]
      uses: ./.github/workflows/publish.yml
      with:
          nexus-path: https://lieberlieber.nexus/repository/lemontree-pipeline-tools
          publish-release: true
      secrets: inherit

    publish-container:
      needs: [prepareVersion,call-build-workflow]
      permissions:
        contents: read
        packages: write
      uses: ./.github/workflows/publishcontainer.yml
      with:
        tags: |
          type=raw,value=${{ github.event.release.tag_name }}
          type=raw,value=latest
